version: "3.9"

services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80" # Host:Container
    volumes:
      - .:/code:cached
    depends_on:
      - db
    environment:
      - DATABASE_URL=${DATABASE_URL}

  db:
    image: mariadb:10.6
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8070:8080 # redirection du port 80 vers 8080 (HTTP) à cause d'apache

volumes:
  mariadb_data:
