version: "3.9"

services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"  # Host:Container
    volumes:
      - .:/code:cached  # ':cached' makes application reload faster
    depends_on:
      - db
    environment:
      - USER=${USER}
      - PASSWORD=${PASSWORD}
      - DATABASE=${DATABASE}

  db:
    image: mariadb:10.6
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DATABASE}
      MYSQL_USER: ${USER}
      MYSQL_PASSWORD: ${PASSWORD}
    ports:
      - "3307:3306"  # Map host port 3307 to container port 3306
    volumes:
      - mariadb_data:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8070:8080  # Redirect port 80 to 8080 (HTTP) because of Apache

volumes:
  mariadb_data:
